import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

import { TRPCReactProvider } from "@/trpc/client";

import { Toaster } from "@/components/ui/sonner";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "I Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang="en" className="dark scroll-smooth">
        <body className={`${lato.className} antialiased`}>
          <Toaster position="top-center" />
          {children}
        </body>
      </html>
    </TRPCReactProvider>
  );
}
